### ISSUE TITLE
sandbox的API是否有问题

### ISSUE THREAD

**Issue by iakc** [Kucoin/kumex-level3-sdk#10]
代码如下：

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import time
import base64
import hmac
import hashlib
import requests

#Example for get balance of accounts in python

api_key = ""
api_secret = ""
api_passphrase = "12345678"
url = 'https://sandbox-api.kumex.com/api/v1/position?symbol=XBTUSDM'
now = int(time.time() * 1000)
str_to_sign = str(now) + 'GET' + '/api/v1/position?symbol=XBTUSDM'
signature = base64.b64encode(
    hmac.new(api_secret.encode('utf-8'), str_to_sign.encode('utf-8'), hashlib.sha256).digest())
headers = { 
    "KC-API-SIGN": signature,
    "KC-API-TIMESTAMP": str(now),
    "KC-API-KEY": api_key,
    "KC-API-PASSPHRASE": api_passphrase
}
response = requests.request('get', url, headers=headers)
print(response.status_code)
print(response.json())
```

得到的结果如下：
```
401
{'success': False, 'code': '404000', 'msg': 'Unauthorized', 'retry': False, 'data': None}
```

**Comment by grape-cola** [comment]
200
{'code': '200000', 'data': {'realisedGrossPnl': 0.0, 'symbol': 'XBTUSDM', 'crossMode': False, 'liquidationPrice': 0.0, 'posLoss': 0.0, 'avgEntryPrice': 0.0, 'unrealisedPnl': 0.0, 'markPrice': 8305.62, 'autoDeposit': False, 'posMargin': 0.0, 'riskLimit': 200, 'unrealisedCost': 0.0, 'posComm': 0.0, 'posMaint': 0.0, 'posCost': 0.0, 'id': '5d9bf60611527a28a73dd978', 'maintMarginReq': 0.005, 'bankruptPrice': 0.0, 'realisedCost': 0.0, 'markValue': 0.0, 'posInit': 0.0, 'realisedPnl': 0.0, 'maintMargin': 0.0, 'realLeverage': 0.0, 'currentCost': 0.0, 'currentQty': 0, 'delevPercentage': 0.0, 'currentComm': 0.0, 'realisedGrossCost': 0.0, 'isOpen': False, 'posCross': 0, 'currentTimestamp': 1570502150875, 'unrealisedRoePcnt': 0, 'unrealisedPnlPcnt': 0}}

没有问题啊，这些请求时需要翻墙的，请问你是否开了翻墙。

**Comment by grape-cola** [comment]
200
{'code': '200000', 'data': {'realisedGrossPnl': 0.0, 'symbol': 'XBTUSDM', 'crossMode': False, 'liquidationPrice': 0.0, 'posLoss': 0.0, 'avgEntryPrice': 0.0, 'unrealisedPnl': 0.0, 'markPrice': 8305.62, 'autoDeposit': False, 'posMargin': 0.0, 'riskLimit': 200, 'unrealisedCost': 0.0, 'posComm': 0.0, 'posMaint': 0.0, 'posCost': 0.0, 'id': '5d9bf60611527a28a73dd978', 'maintMarginReq': 0.005, 'bankruptPrice': 0.0, 'realisedCost': 0.0, 'markValue': 0.0, 'posInit': 0.0, 'realisedPnl': 0.0, 'maintMargin': 0.0, 'realLeverage': 0.0, 'currentCost': 0.0, 'currentQty': 0, 'delevPercentage': 0.0, 'currentComm': 0.0, 'realisedGrossCost': 0.0, 'isOpen': False, 'posCross': 0, 'currentTimestamp': 1570502150875, 'unrealisedRoePcnt': 0, 'unrealisedPnlPcnt': 0}}

Use your code run no problem，The network is best visited abroad

**Comment by iakc** [comment]
连续测了多次，在墙内的时候可以正常返回。
在Vultr建了一台Los Angeles的VPS（操作系统：Ubuntu 19.04，IP地址：149.248.11.233）进行测试时，返回的就是401。
